int _putchar(char c);
int square(int n, int val);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int is_prime_number(int n);
int prime_number(int n, int x);
int is_palindrome(char *s);
int palindrome(char *s, int x, int y);
int is_palin(char *s);
int wildcmp(char *s1, char *s2);
